

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.110.221:3309/aice_log?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 2022aice